#!/bin/bash
docker kill jupyter &> /dev/null
docker rm jupyter &> /dev/null

# https://jupyter-docker-stacks.readthedocs.io/en/latest/index.html

# NB_USER settings
# https://jupyter-docker-stacks.readthedocs.io/en/latest/using/troubleshooting.html Dynamically assign the user ID and GID

# password generated by from notebook.auth import passwd;print(passwd()) as 'dataeng'
# argon2:$argon2id$v=19$m=10240,t=10,p=8$RvtSsYuVJyal5EduF2uRTA$SVSx1a90LWMai55XfViHfyaGJm65m41xygnr/HWnmy4

docker run -d \
    --user root \
    -p 8888:8888 \
    -e NB_UID="$(id -u)" \
    -e NB_GID="$(id -g)"  \
    -e CHOWN_HOME=yes \
    -e CHOWN_HOME_OPTS="-R" \
    -e GRANT_SUDO=yes \
    -e HTTP_PROXY=${HTTP_PROXY} \
    -e HTTPS_PROXY=${HTTPS_PROXY} \
    -e NO_PROXY=${NO_PROXY} \
    -v ${PWD}/home:/home/jovyan/work \
    -w "/home/jovyan/work" \
    --hostname jupyter \
    --name jupyter \
    jupyter_hub_lab:latest \
    start-notebook.sh --NotebookApp.password='argon2:$argon2id$v=19$m=10240,t=10,p=8$RvtSsYuVJyal5EduF2uRTA$SVSx1a90LWMai55XfViHfyaGJm65m41xygnr/HWnmy4'
docker ps
sleep 5
docker logs --tail 30 jupyter
